### Estimating the Value of Pi Using Monte Carlo Simulation

In this section, we use the Monte Carlo simulation method to estimate the value of pi. The idea is to randomly generate points within a square and determine the ratio of points inside a quarter circle inscribed in the square.

```python
# Import the random module for generating random numbers
import random

# Function to estimate the value of pi using Monte Carlo simulation
def estimate_pi(num_points):
    points_inside_circle = 0
    
    for _ in range(num_points):
        x = random.uniform(0, 1)
        y = random.uniform(0, 1)
        
        # Calculating the distance from point (x, y) to the center of the circle (0.5, 0.5)
        distance = (x - 0.5)**2 + (y - 0.5)**2
        
        # If the distance is less than or equal to 0.25 (squared radius), then the point is inside the circle
        if distance <= 0.25:
            points_inside_circle += 1
    
    # The ratio of points inside the circle to the total points is an estimate of pi/4
    estimated_pi = 4 * points_inside_circle / num_points
    return estimated_pi

# Number of points to be used for estimation
num_points = 1000

# Estimate the value of pi using the defined function
estimated_pi = estimate_pi(num_points)

# Print the estimated value of pi
print(f"Estimated value of pi after {num_points} trials is: {estimated_pi}")


In [1]:
import random

def estimate_pi(num_points):
    points_inside_circle = 0
    
    for _ in range(num_points):
        x = random.uniform(0, 1)
        y = random.uniform(0, 1)
        
        # Calculating the distance from point (x, y) to the center of the circle (0.5, 0.5)
        distance = (x - 0.5)**2 + (y - 0.5)**2
        
        # If the distance is less than or equal to 0.25 (squared radius), then the point is inside the circle
        if distance <= 0.25:
            points_inside_circle += 1
    
    # The ratio of points inside the circle to the total points is an estimate of pi/4
    estimated_pi = 4 * points_inside_circle / num_points
    return estimated_pi

num_points = int(input("Enter the number of points to use: "))
estimated_pi = estimate_pi(num_points)
print(f"Estimated value of pi after {num_points} trials is: {estimated_pi}")

Estimated value of pi after 1000 trials is: 3.16


Absolutely! Here's the updated markdown content to explain the result and the concept of improving accuracy by increasing the number of points:

```markdown
### Estimating the Value of Pi Using Monte Carlo Simulation

In this section, we use the Monte Carlo simulation method to estimate the value of pi. The idea is to randomly generate points within a square and determine the ratio of points inside a quarter circle inscribed in the square.

```python
# ... (Previous code remains the same)

# Number of points to be used for estimation
num_points = 1000

# Estimate the value of pi using the defined function
estimated_pi = estimate_pi(num_points)

# Print the estimated value of pi
print(f"Estimated value of pi after {num_points} trials is: {estimated_pi}")
```

The estimated value of pi after 1000 trials is likely to be around 3.16. However, this estimate might not be highly accurate due to the limited number of trials. To improve accuracy, we can increase the `num_points` parameter in the `estimate_pi` function. Let's see how increasing the number of points can lead to a more accurate estimation of pi.

```python
# Number of points for increased accuracy
num_points = 100000

# Estimate the value of pi using the defined function with more points
improved_estimated_pi = estimate_pi(num_points)

# Print the improved estimated value of pi
print(f"Improved estimated value of pi after {num_points} trials is: {improved_estimated_pi}")
```

By increasing the number of points to 100,000, we get a more accurate estimate of pi. The principle here is that as we use more points, the simulation gets closer to the true value of pi. You can experiment further by increasing `num_points` to observe how the accuracy improves.

This concludes the explanation of estimating the value of pi using the Monte Carlo simulation method and the concept of improving accuracy by increasing the number of points.
```

Feel free to include this updated markdown content in your Jupyter Notebook to provide explanations for the code snippet and how accuracy can be improved by adjusting `num_points`.

In [2]:
import random

def estimate_pi(num_points):
    points_inside_circle = 0
    
    for _ in range(num_points):
        x = random.uniform(0, 1)
        y = random.uniform(0, 1)
        
        # Calculating the distance from point (x, y) to the center of the circle (0.5, 0.5)
        distance = (x - 0.5)**2 + (y - 0.5)**2
        
        # If the distance is less than or equal to 0.25 (squared radius), then the point is inside the circle
        if distance <= 0.25:
            points_inside_circle += 1
    
    # The ratio of points inside the circle to the total points is an estimate of pi/4
    estimated_pi = 4 * points_inside_circle / num_points
    return estimated_pi

num_points = int(input("Enter the number of points to use: "))
estimated_pi = estimate_pi(num_points)
print(f"Estimated value of pi after {num_points} trials is: {estimated_pi}")

Estimated value of pi after 1000000 trials is: 3.14024


Absolutely! Here's the concluding markdown content that summarizes the result and explains the significance of the outcome:

```markdown
### Conclusion: Estimating Pi Using Monte Carlo Simulation

In this section, we employed the Monte Carlo simulation method to estimate the value of pi. By randomly generating points within a square and calculating the ratio of points falling inside a quarter circle inscribed in the square, we approximated the value of pi.

```python
# ... (Code for estimation and explanation)

# Number of points for increased accuracy
num_points = 100000

# Estimate the value of pi using the defined function with more points
improved_estimated_pi = estimate_pi(num_points)

# Print the improved estimated value of pi
print(f"Improved estimated value of pi after {num_points} trials is: {improved_estimated_pi}")
```

After increasing the number of points to 100,000, we obtained an estimate that closely approaches the value of pi, around 3.14. This outcome demonstrates the principle that as we use more points, our estimation becomes more accurate and converges towards the actual value.

Estimating pi using the Monte Carlo simulation provides insight into how random sampling can be used to solve mathematical problems. By adjusting the number of points, we can control the trade-off between computational resources and the accuracy of our estimation.

In summary, the Monte Carlo method offers a versatile approach to approximating complex values like pi, making it a valuable tool for various applications in mathematics, science, and engineering.

This concludes the exploration of estimating pi using the Monte Carlo simulation method and understanding the impact of the number of points on accuracy.
```

Feel free to include this concluding markdown content in your Jupyter Notebook to wrap up the explanation of estimating pi through the Monte Carlo simulation and its accuracy implications.

# BONUS : PYGAME IMPLEMENTATION

In [6]:
import pygame
import random

# Initialize Pygame
pygame.init()

# Screen dimensions
screen_width = 400
screen_height = 400

# Colors
blue = (0, 0, 255)
red = (255, 0, 0)

# Create the Pygame screen
screen = pygame.display.set_mode((screen_width, screen_height))
pygame.display.set_caption("Monte Carlo Pi Estimation")

# Function to estimate pi using Monte Carlo simulation
def estimate_pi(num_points):
    points_inside_circle = 0
    
    for _ in range(num_points):
        x = random.uniform(0, 1)
        y = random.uniform(0, 1)
        
        # Calculating the distance from point (x, y) to the center of the circle (0.5, 0.5)
        distance = (x - 0.5)**2 + (y - 0.5)**2
        
        # If the distance is less than or equal to 0.25 (squared radius), then the point is inside the circle
        if distance <= 0.25:
            points_inside_circle += 1
    
    # The ratio of points inside the circle to the total points is an estimate of pi/4
    estimated_pi = 4 * points_inside_circle / num_points
    return estimated_pi

# Number of points for estimation
num_points = 100

# Estimate pi
estimated_pi = estimate_pi(num_points)
print(f"Estimated value of pi after {num_points} trials is: {estimated_pi}")

# Frame rate control
clock = pygame.time.Clock()
frame_rate = 10  # Adjust the frame rate here

# Main loop for Pygame visualization
running = True
points_plotted = 0
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
    
    # Draw the quarter circle
    pygame.draw.arc(screen, blue, (0, 0, screen_width, screen_height), 0, 90, 1)
    
    # Monte Carlo simulation
    for _ in range(num_points - points_plotted):
        x = random.uniform(0, 1) * screen_width
        y = random.uniform(0, 1) * screen_height
        
        distance = (x - screen_width / 2)**2 + (y - screen_height / 2)**2
        
        if distance <= (screen_width / 2)**2:
            pygame.draw.circle(screen, blue, (int(x), int(y)), 1)
        else:
            pygame.draw.circle(screen, red, (int(x), int(y)), 1)
    
    pygame.display.flip()  # Update the screen
    points_plotted += num_points - points_plotted
    
    clock.tick(frame_rate)  # Limit the frame rate

    # Automatically exit when all points are plotted
    if points_plotted >= num_points:
        running = False

# Quit Pygame
pygame.quit()


Estimated value of pi after 100 trials is: 2.96
